layout_spectrum: 0.22334779589436948
typography_spectrum: 0.05790590378455818
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.8514267920982093
  lightness: 0.21175175695680082
  saturation: 0.018510857364162803
  rhythmicContrast: 0.7739339433610439
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/915af64a-6e2a-4ca0-aac5-fb6b325e8b73.png
  type: Post
  appId: '1686033208385756'
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cf3ac889-923e-44b5-81ba-0b82f2f39686.png
name: Sanjayvision
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: bd59c6c4-8fce-4b6f-81a5-a5d6636882b1
    type: content
  - name: IMDB
    id: 88289417-e0c2-429c-ae33-906532d819b0
    type: content
  - name: Instagram
    id: 2dfd16ec-5b7b-4a52-8c61-be9956da9e6a
    type: content
  - name: Twitter
    url: 'https://twitter.com/sanjayradio'
    type: external
  - name: LinkedIn
    id: 0e4cbbde-0cf5-424b-bfa9-b7764677df28
    type: content
favicon: null
title: Neil Sanjay Singh | Creator
description: The life I tell you about.
purpose: []
