typography_spectrum: 0.28804
color:
  brandColors:
    - '#ebebeb'
    - '#a2a2a2'
    - '#343434'
    - '#6d6d6d'
    - '#151515'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: sanjayvision
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Neil Sanjay Singh | Creator
purpose: []
