typography_spectrum: 0.28804
color:
  brandColors:
    - '#ebebeb'
    - '#a2a2a2'
    - '#343434'
    - '#6d6d6d'
    - '#151515'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/915af64a-6e2a-4ca0-aac5-fb6b325e8b73.png
  type: Post
  appId: '1686033208385756'
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cf3ac889-923e-44b5-81ba-0b82f2f39686.png
name: Sanjayvision
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: bd59c6c4-8fce-4b6f-81a5-a5d6636882b1
    type: content
  - name: IMDB
    id: 88289417-e0c2-429c-ae33-906532d819b0
    type: content
  - name: Instagram
    id: 2dfd16ec-5b7b-4a52-8c61-be9956da9e6a
    type: content
  - name: Twitter
    url: 'https://twitter.com/sanjayradio'
    type: external
favicon: null
title: Neil Sanjay Singh | Creator
description: The life I tell you about.
purpose: []
