name: sanjayvision
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28804
title: 'Neil Sanjay Singh | Creator'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#a2a2a2'
    - '#343434'
    - '#6d6d6d'
    - '#151515'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
