name: sanjayvision
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28804
title: 'Neil Sanjay Singh | Creator'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#a2a2a2'
    - '#343434'
    - '#6d6d6d'
    - '#151515'
  brandStrength: 0.8455768192652613
  lightness: 0.27953975554555655
  saturation: 0.009925637161359191
  rhythmicContrast: 0.31344670872204006
purpose: []
