typography_spectrum: 0.05790590378455818
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.8514267920982093
  lightness: 0.21175175695680082
  saturation: 0.018510857364162803
  rhythmicContrast: 0.7739339433610439
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3cf5bf6a-e30f-4291-bb96-9fd2dd263f50.png
  type: Post
  appId: '1686033208385756'
layout_spectrum: 0.22334779589436948
analytics:
  google: UA-83265665-1
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/98d2bd20-8a9f-42dc-8e9b-dc8f8d99ff70.png
name: Public Use Only
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: bd59c6c4-8fce-4b6f-81a5-a5d6636882b1
    type: content
  - name: IMDB
    url: 'http://www.imdb.me/sanjayvision?ref_=pro_nm_nav_ov_vanity'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/sanjayvision/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/sanjayradio'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/sanjayvision/'
    type: external
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/sanjayvision'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f8b8fc7c-e295-47c3-8517-ed3de069c197.png
title: Neil Sanjay Singh | Creator
description: The life I tell you about.
purpose: []
