name: sanjayvision
favicon: null
layout_spectrum: 0.6676386478357017
typography_spectrum: 0.9172498544212431
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8455768192652613
  lightness: 0.27953975554555655
  saturation: 0.009925637161359191
  rhythmicContrast: 0.31344670872204006
purpose: []
